import Head from 'next/head';
import Link from 'next/link';
import { client } from '../libs/client';

export default function Home({ blog }) {
	return (
		<div className=''>
			<Head>
				<title>My Blog</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<header className='border-b-slate-300 border-b-[1px] px-8'>
				<h1 className='text-2xl my-4'>myBlog</h1>
			</header>
			<main className='max-w-5xl mx-auto p-4 flex flex-wrap justify-between'>
				<div className='flex-grow outline p-6 outline-red-400'>
					<h2 className='text-3xl'>記事一覧</h2>
					<ul className='mt-10 text-lg space-y-8'>
						{blog.map((post) => (
							<li key={post.id}>
								<Link href={`/blog/${post.id}`}>
									<a className='font-bold'>{post.title}</a>
								</Link>
								<p className='mt-1'>{post.createdAt}</p>
							</li>
						))}
					</ul>
				</div>
				<aside className='w-[300px] p-4 outline outline-green-400'>
					<div>Search</div>
					<div>
						<h2>カテゴリー</h2>
					</div>
				</aside>
			</main>
			<footer></footer>
		</div>
	);
}

export const getStaticProps = async () => {
	const data = await client.get({ endpoint: 'blog' });

	return {
		props: {
			blog: data.contents,
		},
	};
};
